CREATE SCHEMA IF NOT EXISTS intake_auditor;

CREATE TABLE IF NOT EXISTS intake_auditor.audit_runs (
  id uuid PRIMARY KEY,
  generated_at timestamptz NOT NULL,
  file_path text NOT NULL,
  total_rows integer NOT NULL,
  missing_headers jsonb NOT NULL,
  missing_values jsonb NOT NULL,
  field_completeness jsonb NOT NULL,
  complete_required_rows integer NOT NULL,
  complete_required_rows_pct numeric(5, 2) NOT NULL,
  duplicate_emails jsonb NOT NULL,
  duplicate_applicant_ids jsonb NOT NULL,
  status_distribution jsonb NOT NULL,
  stage_distribution jsonb NOT NULL,
  program_distribution jsonb NOT NULL,
  program_required_completeness jsonb NOT NULL,
  score_stats jsonb,
  score_stats_by_program jsonb NOT NULL,
  score_stats_by_status jsonb NOT NULL,
  submission_window jsonb,
  submission_age_days_stats jsonb,
  submission_gap_stats jsonb,
  recent_submissions integer NOT NULL,
  recent_submissions_by_program jsonb NOT NULL,
  recent_submission_window_days integer NOT NULL,
  stale_submission_window_days integer NOT NULL,
  invalid_email_count integer NOT NULL,
  invalid_score_count integer NOT NULL,
  score_out_of_range_count integer NOT NULL,
  invalid_submitted_at_count integer NOT NULL,
  future_submissions_count integer NOT NULL,
  stale_submissions_count integer NOT NULL,
  stale_submissions_by_program jsonb NOT NULL,
  unknown_status_count integer NOT NULL,
  unknown_stage_count integer NOT NULL,
  blank_status integer NOT NULL,
  blank_stage integer NOT NULL,
  blank_program integer NOT NULL,
  email_domain_distribution jsonb NOT NULL,
  status_stage_distribution jsonb NOT NULL,
  program_status_distribution jsonb NOT NULL,
  submission_weekday_distribution jsonb NOT NULL,
  submission_hour_distribution jsonb NOT NULL,
  submission_recency_buckets jsonb NOT NULL,
  submission_recency_by_program jsonb NOT NULL,
  submission_daily_trend jsonb NOT NULL,
  submission_weekly_trend jsonb NOT NULL,
  issue_count integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audit_runs_generated_at_idx
  ON intake_auditor.audit_runs (generated_at DESC);
